// Brand book (brand/index.html), design-token exports and the concept index (index.html).
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import * as L from './lib.mjs';
const { esc, icon, frame, sym, terrainSvg, settings, agents, towns, listings, guides, journeys, terrain } = L;
const ROOT = new URL('../', import.meta.url);
const W = (p, s) => { const u = new URL(p, ROOT); mkdirSync(new URL('./', u), { recursive: true }); writeFileSync(u, s); };
const palette = JSON.parse(readFileSync(new URL('../data/palette.json', import.meta.url)));
const C = palette.colors;

// ---------------------------------------------------------------- tokens export
const tokens = {
  $schema: 'Oberdorfer Team design tokens · Concept 2 (The Quadrangle)',
  color: Object.fromEntries(Object.entries(C).map(([k, v]) => [k, { value: v.oklch, hex: v.hex }])),
  font: { serif: 'Besley (400, 400 italic, 600, 800, 800 italic)', sans: 'Overpass (variable 100–900, roman + italic)', mono: 'Overpass Mono 500 — codes, coordinates, MLS numbers only' },
  type: { display: 'clamp(3.25rem, 1.6rem + 6.2vw, 6rem)', h1: 'clamp(2.5rem, 1.55rem + 3.6vw, 4.25rem)', h2: 'clamp(1.85rem, 1.35rem + 1.9vw, 3rem)', h3: 'clamp(1.3rem, 1.15rem + 0.55vw, 1.6rem)', lede: 'clamp(1.15rem, 1.06rem + 0.4vw, 1.375rem)', body: '1.0625rem', small: '0.9375rem', label: '0.8125rem', price: 'clamp(1.75rem, 1.45rem + 1.1vw, 2.5rem)', trackTown: '0.32em', trackLabel: '0.08em' },
  space: { 1: '0.25rem', 2: '0.5rem', 3: '0.75rem', 4: '1rem', 5: '1.5rem', 6: '2rem', 7: '3rem', 8: '4rem', 9: '6rem', 10: '8rem', section: 'clamp(4rem, 2.5rem + 6vw, 8rem)', collar: 'clamp(10px, 2.6vw, 40px)', gutter: 'clamp(16px, 2.2vw, 32px)' },
  line: { neatline: '1.5px', hair: '1px', radius: '2px' },
  motion: { easeOut: 'cubic-bezier(0.16, 1, 0.3, 1)', easeInOut: 'cubic-bezier(0.65, 0, 0.35, 1)', fast: '160ms', base: '320ms', slow: '700ms', draw: '1800ms' },
};
W('assets/brand/tokens.json', JSON.stringify(tokens, null, 2));
const themeJson = {
  $schema: 'https://schemas.wp.org/trunk/theme.json', version: 3,
  settings: {
    color: { defaultPalette: false, defaultGradients: false, gradients: [], palette: Object.entries(C).map(([slug, v]) => ({ slug, name: slug.replace(/-/g, ' ').replace(/^./, c => c.toUpperCase()), color: v.hex })) },
    typography: { defaultFontSizes: false, fluid: true, fontFamilies: [
      { slug: 'serif', name: 'Besley', fontFamily: '"Besley", Georgia, serif', fontFace: [['400', 'normal'], ['400', 'italic'], ['600', 'normal'], ['800', 'normal'], ['800', 'italic']].map(([w, s]) => ({ fontFamily: 'Besley', fontWeight: w, fontStyle: s, src: [`file:./assets/fonts/besley-latin-${w}-${s}.woff2`] })) },
      { slug: 'sans', name: 'Overpass', fontFamily: '"Overpass", "Helvetica Neue", Arial, sans-serif', fontFace: [{ fontFamily: 'Overpass', fontWeight: '100 900', fontStyle: 'normal', src: ['file:./assets/fonts/overpass-latin-wght-normal.woff2'] }, { fontFamily: 'Overpass', fontWeight: '100 900', fontStyle: 'italic', src: ['file:./assets/fonts/overpass-latin-wght-italic.woff2'] }] },
      { slug: 'mono', name: 'Overpass Mono', fontFamily: '"Overpass Mono", ui-monospace, monospace', fontFace: [{ fontFamily: 'Overpass Mono', fontWeight: '500', fontStyle: 'normal', src: ['file:./assets/fonts/overpass-mono-latin-500-normal.woff2'] }] }],
      fontSizes: Object.entries({ small: '0.9375rem', body: '1.0625rem', lede: '1.375rem', h3: '1.6rem', h2: '3rem', h1: '4.25rem', display: '6rem' }).map(([slug, size]) => ({ slug, name: slug, size })) },
    spacing: { defaultSpacingSizes: false, spacingSizes: [['20', '0.5rem'], ['30', '0.75rem'], ['40', '1rem'], ['50', '1.5rem'], ['60', '2rem'], ['70', '3rem'], ['80', '4rem'], ['90', '6rem']].map(([slug, size]) => ({ slug, name: slug, size })) },
    layout: { contentSize: '66ch', wideSize: '1520px' },
    border: { radius: true },
  },
  styles: { color: { background: 'var(--wp--preset--color--paper)', text: 'var(--wp--preset--color--ink)' }, typography: { fontFamily: 'var(--wp--preset--font-family--sans)', fontSize: 'var(--wp--preset--font-size--body)', lineHeight: '1.6' },
    elements: { heading: { typography: { fontFamily: 'var(--wp--preset--font-family--serif)', fontWeight: '600' } }, link: { color: { text: 'var(--wp--preset--color--water)' } }, button: { color: { background: 'var(--wp--preset--color--route)', text: 'var(--wp--preset--color--paper)' }, border: { radius: '2px' }, typography: { fontWeight: '700' } } } },
};
W('assets/brand/theme.json', JSON.stringify(themeJson, null, 2));

// ---------------------------------------------------------------- brand book
const p = '../';
const CH = [
  ['purpose', 'Purpose'], ['positioning', 'Positioning'], ['audience', 'Audience'], ['personality', 'Personality & values'], ['voice', 'Voice & tone'], ['messaging', 'Messaging'],
  ['logo', 'Logo'], ['attribution', 'Brokerage attribution'], ['type', 'Typography'], ['color', 'Color'], ['photography', 'Photography'], ['cartography', 'The sheet: cartography'],
  ['layout', 'Layout & grid'], ['components', 'Components'], ['motion', 'Motion'], ['accessibility', 'Accessibility & fairness'], ['tokens', 'Design tokens'], ['model', 'Content model'],
];
const chap = (id, i, title, lede, body) => `<section class="chapter" id="${id}" aria-labelledby="h-${id}"><header class="chapter__head"><span class="chapter__n">${String(i + 1).padStart(2, '0')}</span><h2 id="h-${id}">${title}</h2>${lede ? `<p>${lede}</p>` : ''}</header>${body}</section>`;
const swatchRoles = {
  paper: 'The sheet. Default ground for every page.', 'paper-deep': 'Collar strips, panels, data-block headers.', woodland: 'Woodland tint: place frames, highlight fields, contact bands.', 'woodland-deep': 'Selection, hover on woodland.',
  forest: 'Brand field. Drenched bands, mark, positive states.', 'forest-deep': 'Deepest field; code blocks, menus.', 'forest-tint': 'Secondary text and mark on forest.', ink: 'Culture ink: text, neatlines, controls.', 'ink-soft': 'Secondary text, labels.', 'ink-faint': 'Large type and marks only (3.99:1).',
  contour: 'Contour linework. Never text.', 'contour-ink': 'Contour-colored text: sample tags, numerals in notes.', clay: 'Property frames.', water: 'Links and information.', 'water-tint': 'People frames.', 'water-light': 'Water and links on dark fields.', route: 'Primary routes: the main action, selected states.', 'route-deep': 'Hover/pressed route.', 'route-tint': 'Open-house and alert fields.',
};
const allShots = [
  ...towns.map(t => ({ ...t.photo, kind: 'place', use: `${t.name} town page` })),
  ...guides.map(g => ({ ...g.photo, kind: g.photo.code.startsWith('PE') ? 'people' : g.photo.code.startsWith('PR') ? 'property' : 'place', use: `Field Guide: ${g.title}` })),
  ...agents.map(a => ({ ...a.portrait, kind: 'people', use: `${a.name} portrait` })),
  ...listings.flatMap(l => l.photos.map(ph => ({ ...ph, use: `${l.address} (sample listing)` }))),
];
const relSvg = `<svg viewBox="0 0 900 330" role="img" aria-labelledby="rel-t"><title id="rel-t">Content relationships: agents are members of the team; the team is affiliated with the brokerage; agents relate to listings, communities and articles.</title>
<defs><marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="var(--contour-ink)"/></marker></defs>
<path class="edge" d="M450 72 V118" marker-end="url(#ah)"/><text class="lbl" x="462" y="100">affiliated with</text>
<path class="edge" d="M450 214 V172" marker-end="url(#ah)"/><text class="lbl" x="462" y="198">member of</text>
<path class="edge" d="M380 250 C 280 250 220 260 168 278" marker-end="url(#ah)"/><text class="lbl" x="232" y="246">lists</text>
<path class="edge" d="M450 262 V280" marker-end="url(#ah)"/><text class="lbl" x="462" y="276">serves</text>
<path class="edge" d="M520 250 C 620 250 680 260 732 278" marker-end="url(#ah)"/><text class="lbl" x="616" y="246">writes</text>
<g class="node brk"><rect x="330" y="20" width="240" height="52"/><text x="450" y="51" text-anchor="middle">Brokerage (settings, swappable)</text></g>
<g class="node team"><rect x="330" y="120" width="240" height="52"/><text x="450" y="151" text-anchor="middle">The Oberdorfer Team</text></g>
<g class="node"><rect x="380" y="214" width="140" height="48"/><text x="450" y="243" text-anchor="middle">Agent</text></g>
<g class="node"><rect x="40" y="280" width="160" height="44"/><text x="120" y="307" text-anchor="middle">Property</text></g>
<g class="node"><rect x="370" y="282" width="160" height="44"/><text x="450" y="309" text-anchor="middle">Community</text></g>
<g class="node"><rect x="700" y="280" width="160" height="44"/><text x="780" y="307" text-anchor="middle">Guide / Market update</text></g>
</svg>`;

const body = `
<section class="bb-cover" aria-labelledby="bb-h">
  <div class="mapbox" aria-hidden="true"><div class="stage stage--cover">${terrainSvg(p, { aspect: 'xMidYMid meet', draw: true })}${terrain.towns.filter(t => t.x > 0.45).map(t => `<span class="town-pin" style="--x:${t.x};--y:${t.y};pointer-events:none"><span class="town halo">${t.name}</span></span>`).join('')}</div></div>
  <div class="bb-cover__inner">
    <h1 id="bb-h">The Oberdorfer Team <em>brand book.</em></h1>
    <p>Concept 2 · The Quadrangle. A brand that frames place the way a survey sheet frames ground: neatline, collar, legend, adjoining sheets, and the people who read it with you.</p>
  </div>
  <div class="opening__collar"><span class="credit">Prepared for <b>The Oberdorfer Team</b> · a real estate team at ${esc(settings.brokerage.legalName)}</span><span class="scalebar" aria-hidden="true"><span class="scalebar__bar"><span></span><span></span><span></span><span></span></span>Edition 1 · October 2026</span><a href="${p}site/">See the website concept →</a></div>
</section>
<div class="bb-layout">
<nav class="bb-toc" aria-label="Brand book contents"><h2>Contents</h2><ol>${CH.map(([id, t]) => `<li><a href="#${id}">${t}</a></li>`).join('')}</ol></nav>
<div>
${chap('purpose', 0, 'Why we <em>exist</em>', 'To help people find their place in Central Massachusetts, and to handle the move as if it were our own.', `
<div class="bb-grid"><div class="span-7 prose"><p>A move is never only about a house. It’s about a street, a town, a commute, a season of life. Most real estate websites flatten all of that into a grid of photos and a price filter, then hand the visitor to whoever answers the lead first.</p><p>The Oberdorfer Team exists to do the opposite: to read the ground with people, slowly and specifically, and to stay personally responsible from the first conversation to the closing table. The brand has one job: to make that difference visible before anyone calls.</p></div>
<div class="span-5"><p class="statement">Find your place. <em>We’ll handle the rest, personally.</em></p></div></div>`)}
${chap('positioning', 1, 'Where we <em>stand</em>', 'A team-owned local practice, not a portal and not a luxury boutique.', `
<div class="bb-grid"><div class="span-6"><dl class="hier"><div><dt>For</dt><dd class="prose">People buying, selling or moving within Central Massachusetts, who want a knowledgeable local person more than a feed of listings.</dd></div><div><dt>We are</dt><dd class="prose">The Oberdorfer Team, a small real estate team at REWAP Brokerage, led by Brandon and Kait Oberdorfer.</dd></div><div><dt>Who</dt><dd class="prose">reads homes in the context of their streets and towns, and stays personally responsible for every move.</dd></div><div><dt>Unlike</dt><dd class="prose">listing portals and large franchises, where you meet a call center first and a person later.</dd></div><div><dt>Because</dt><dd class="prose">our name is on the door, our towns are on the sheet, and our facts are kept separate from our opinions.</dd></div></dl></div>
<div class="span-6"><h3>What we are not</h3><ul class="ruled"><li><b>A portal</b><span>We don’t compete on volume. Search is excellent because people expect it, but the product is guidance.</span></li><li><b>A luxury brand</b><span>No black and gold, no velvet adjectives. Every price point gets the same care.</span></li><li><b>A funnel</b><span>Forms start conversations. Nothing on the site pressures, counts down or traps.</span></li><li><b>The brokerage</b><span>REWAP is our brokerage affiliation, named clearly and kept in its place. We never present as an independent brokerage.</span></li></ul></div></div>`)}
${chap('audience', 2, 'Who we’re <em>talking to</em>', 'Four kinds of visitor, often the same person at different moments.', `
<div class="bb-grid">${[['Buyers', 'route', 'Want to find homes fast, then understand them. Need: excellent search, honest context, a person to tour with.', 'Hear: “Here’s what this house is like, and what it will take.”'], ['Sellers', 'double', 'Want a price they can trust and a plan they can see. Need: a real pricing conversation, preparation help, calm negotiation.', 'Hear: “Here’s our reasoning. You decide.”'], ['Relocators', 'dashed', 'Know the region by name only. Need: orientation by commute, space and street character, without demographic steering.', 'Hear: “Let’s see three towns in one afternoon.”'], ['Explorers', 'contour', 'Not moving this year. Need: content worth reading, a reason to come back, no pressure.', 'Hear: “Here’s something you didn’t know about where you live.”']].map(([n, s, need, hear]) => `<div class="span-6" style="border-top:var(--neatline) solid var(--ink);padding-top:1rem">${sym(s)}<h3 style="margin-top:.75rem">${n}</h3><p class="prose" style="font-size:1.0625rem">${need}</p><p class="meta" style="margin-top:.6rem;font-style:italic">${hear}</p></div>`).join('')}</div>`)}
${chap('personality', 3, 'Personality <em>& values</em>', 'Nine words from the brief, held in three groups so they can be used.', `
<div class="bb-grid"><div class="span-12"><dl class="hier">${[['Grounded', 'Local · knowledgeable · thoughtful', 'We know the side streets and say what we know plainly. Specifics over superlatives.'], ['Steady', 'Calm · trustworthy · responsive', 'Even when the market isn’t. Fast replies, unhurried judgment.'], ['Contemporary', 'Modern · cultured · warm', 'Care in typography and photography, warmth in words; never stuffy, never trendy.']].map(([a, b, c]) => `<div><dt>${a}</dt><dd><b style="font:600 1.125rem var(--f-serif)">${b}</b><p class="meta" style="margin-top:.3rem">${c}</p></dd></div>`).join('')}</dl></div>
<div class="span-12"><h3>Values</h3><ul class="ruled">${[['Personal', 'You always know who is handling your move, by name.'], ['Specific', 'We describe the actual street, the actual light, the actual drive.'], ['Factual', 'Facts are verified and labeled; opinions are signed. We never invent a figure.'], ['Fair', 'We describe places and housing, never who lives there.'], ['Owned', 'Our brand, content and relationships belong to the team and travel with us.']].map(([a, b]) => `<li><b>${a}</b><span>${b}</span></li>`).join('')}</ul></div></div>`)}
${chap('voice', 4, 'Voice <em>& tone</em>', 'Write like a knowledgeable neighbor who happens to be very good at this.', `
<div class="bb-grid"><div class="span-5"><h3>Principles</h3><ul class="ruled"><li><b>Concrete</b><span>Name the street, the room, the hour. “The kitchen gets light until four” beats “sun-drenched.”</span></li><li><b>Short</b><span>Sentences that can be said out loud. One idea each.</span></li><li><b>Signed</b><span>Opinions carry a name. Facts carry a source.</span></li><li><b>Unhurried</b><span>No countdowns, no “act now,” no exclamation marks in calls to action.</span></li><li><b>Plain about money</b><span>Prices, fees and timelines stated clearly, early.</span></li></ul></div>
<div class="span-7 pairs">${[['Stunning move-in-ready gem in a sought-after neighborhood!', 'A 1957 ranch, renovated by someone who liked it the way it was. Two streets up from the lake.'], ['Contact us today to get your FREE home valuation!', 'Ask for a pricing conversation. We’ll walk through the house, then explain a range and our reasoning.'], ['Great family neighborhood with top-rated schools.', 'Capes and colonials on established streets, a short drive to I-290. (We describe places and housing, not who lives there.)'], ['Submit', 'Send to Kait']].map(([no, yes]) => `<div class="pair"><div class="no"><h3 class="h4">${icon(p, 'close')}Not this</h3><p>${no}</p></div><div class="yes"><h3 class="h4">${icon(p, 'check')}This</h3><p>${yes}</p></div></div>`).join('')}</div>
<div class="span-12"><h3>Tone by moment</h3><ul class="ruled"><li><b>Property story</b><span>Observational and warm; written after walking the house; signed. Clearly separate from data.</span></li><li><b>Town page</b><span>Specific and even-handed. Housing, places, getting around. No rankings, no “best,” no demographics.</span></li><li><b>Calls to action</b><span>Name the human and the next step: “Ask about this home,” “Schedule a showing,” “Talk with Brandon.”</span></li><li><b>Errors & empty states</b><span>Say what happened and what to do: “No homes match all of that. Try fewer filters, or ask us to watch for it.”</span></li><li><b>Legal & disclosure</b><span>Plain, complete, never hidden; set in the collar where readers expect it.</span></li></ul></div></div>`)}
${chap('messaging', 5, 'Messaging <em>hierarchy</em>', 'From the idea to the button. Each level earns the next.', `
<dl class="hier">
<div><dt>Brand idea</dt><dd><p class="statement" style="font-size:2.25rem">Find your place.</p><p class="meta">The organizing idea, not necessarily printed. “Place” spans a home, a street, a town, a stage of life.</p></dd></div>
<div><dt>Tagline</dt><dd><p class="statement" style="font-size:2rem"><em>Let’s</em> find your place.</p><p class="meta">Proposed. One word turns the idea into an offer of company: the personal handling is in the “let’s.” Used on signs, social and email footers; the homepage states the idea itself.</p></dd></div>
<div><dt>Promise</dt><dd><p class="statement" style="font-size:1.75rem">Real estate, <em>personally handled.</em></p><p class="meta">Supporting line. Used where the team is introduced.</p></dd></div>
<div><dt>Pillars</dt><dd><ul class="ruled" style="border-top:0"><li><b>Place</b><span>We read homes in the context of streets, towns and seasons. Proof: town sheets, the Field Guide, property stories.</span></li><li><b>People</b><span>You always know who is handling your move. Proof: named contacts on every page, direct lines, signed writing.</span></li><li><b>Facts</b><span>Verified data and opinion never mix. Proof: labeled data blocks, sources, no invented statistics.</span></li></ul></dd></div>
<div><dt>Action vocabulary</dt><dd><p class="prose" style="font-size:1rem">Ask about this home · Schedule a showing · Talk about selling · Ask for a pricing conversation · Ask about this town · Planning a move? · Talk with Kait · Send to Brandon · Save this search</p><p class="meta" style="margin-top:.4rem">Never: Contact us · Submit · Get started · Learn more.</p></dd></div>
</dl>`)}
${chap('logo', 6, 'The <em>mark</em>', 'Three contour rings of one small hill, its summit set to the northwest. An “O” for Oberdorfer, and a place on a map.', `
<div class="bb-grid">
<div class="span-6 construction"><div class="plate" style="min-height:360px"><svg viewBox="-8 -8 64 64" aria-hidden="true"><g stroke="var(--rule-strong)" stroke-width=".25" fill="none"><circle cx="24" cy="24" r="20.6"/><line x1="-8" y1="24" x2="56" y2="24"/><line x1="24" y1="-8" x2="24" y2="56"/><circle cx="21.8" cy="21.4" r="6.5" stroke-dasharray="1 1"/></g><g fill="none" stroke="var(--forest)" stroke-width="2.9" stroke-linejoin="round">${L.mark.rings.map(d => `<path d="${d}"/>`).join('')}</g><circle cx="20.6" cy="20.2" r=".9" fill="var(--route)"/></svg><span class="plate__cap">Construction · 48-unit grid · stroke 2.9u · rings offset toward NW · red dot marks the summit</span></div></div>
<div class="span-6 prose"><p>The rings are drawn from the same family of curves as the site’s terrain, so the mark and the map feel like one hand. The innermost ring is offset toward the upper left: the hill is steeper on its southeast side, the way glacial drumlins in this region are.</p><p>Never redraw the rings, fill them, or add a pin, roof or key. At small sizes (below 20px) use the favicon, which sets the mark in paper on a forest square.</p></div>
<div class="span-12 plates">
  <div class="plate"><img src="${p}assets/brand/logo-horizontal-attribution.svg" alt="The Oberdorfer Team at REWAP Brokerage, horizontal lockup" width="560" style="width:min(560px,100%)"><span class="plate__cap">Primary · horizontal with attribution</span></div>
  <div class="plate plate--forest"><img src="${p}assets/brand/logo-horizontal-reversed.svg" alt="Reversed horizontal lockup on forest" width="560" style="width:min(560px,100%)"><span class="plate__cap">Reversed · on forest only</span></div>
  <div class="plate plate--woodland"><img src="${p}assets/brand/logo-stacked-attribution.svg" alt="Stacked lockup" width="260" style="width:min(260px,70%)"><span class="plate__cap">Stacked · signs, social avatars, print</span></div>
  <div class="plate"><div style="display:flex;gap:2.5rem;align-items:center;flex-wrap:wrap;justify-content:center"><img src="${p}assets/brand/mark.svg" alt="Mark" width="120"><img src="${p}assets/brand/mark.svg" alt="" width="48"><img src="${p}assets/brand/mark.svg" alt="" width="24"><img src="${p}assets/brand/favicon.svg" alt="Favicon" width="32"></div><span class="plate__cap">Mark alone · 120 / 48 / 24px · favicon below 20px</span></div>
</div>
<div class="span-6"><h3>Clear space & size</h3><ul class="ruled"><li><b>Clear space</b><span>The height of the mark’s middle ring on every side. Nothing enters it, including the brokerage line.</span></li><li><b>Minimum</b><span>Horizontal lockup 160px wide on screen, 38mm in print. Attribution line never below 8px.</span></li><li><b>Wordmark</b><span>“The” and “Team” in Besley italic; “Oberdorfer” in Besley ExtraBold. Never retype it; use the supplied SVGs.</span></li></ul></div>
<div class="span-6"><h3>Downloads</h3><div class="dl-list">${['logo-horizontal-attribution', 'logo-horizontal', 'logo-horizontal-reversed', 'logo-stacked-attribution', 'logo-stacked', 'mark', 'mark-reversed', 'mark-ink', 'favicon'].map(f => `<a class="btn btn--line btn--small" href="${p}assets/brand/${f}.svg" download>${f}.svg</a>`).join('')}</div></div>
<div class="span-12"><h3>Misuse</h3><div class="misuse">
  <figure><div class="plate"><img src="${p}assets/brand/logo-horizontal.svg" alt="" style="width:90%;transform:scaleX(1.35)"></div><figcaption>Don’t stretch or condense.</figcaption></figure>
  <figure><div class="plate" style="background:var(--route)"><img src="${p}assets/brand/logo-horizontal-reversed.svg" alt="" style="width:90%"></div><figcaption>Don’t place on route red or photography without a field.</figcaption></figure>
  <figure><div class="plate"><span style="display:flex;align-items:center;gap:8px"><img src="${p}assets/brand/mark.svg" alt="" width="34"><b style="font:800 1.4rem Arial">Oberdorfer Team</b></span></div><figcaption>Don’t retype the wordmark in another face.</figcaption></figure>
  <figure><div class="plate"><span style="display:grid;justify-items:center;gap:6px"><b style="font:800 1.1rem var(--f-sans);letter-spacing:.1em">REWAP BROKERAGE</b><img src="${p}assets/brand/logo-horizontal.svg" alt="" style="width:70%"></span></div><figcaption>Don’t lead with the brokerage or enlarge it.</figcaption></figure>
</div></div></div>`)}
${chap('attribution', 7, 'Brokerage <em>attribution</em>', 'The team leads; the brokerage is named clearly, consistently and one step down. Never omitted, never dominant.', `
<div class="bb-grid"><div class="span-5 prose"><p>Every surface carries an attribution set by context, from a three-word line in the header to the full disclosure in the footer. All wording lives in one settings file (<code>data/settings.json</code>, a WordPress options page in production), so compliance language can change without touching templates, and a future change of brokerage means editing settings, not rebuilding the site.</p><p>Rule of thumb: the brokerage name is set in the sans at label size or body size, never in the serif display, never larger than the team name, and never with a logo unless the brokerage requires one.</p></div>
<div class="span-7"><div class="attr-demo">
  <div><code>header</code><div>${L.lockup(p, {})}</div></div>
  <div><code>footer</code><p class="meta">${esc(settings.attribution.footer)}</p></div>
  <div><code>agent</code><div class="attr-line" style="border:0;padding:0">${L.markSvg('')}<span>${esc(settings.attribution.agent.replace('{name}', 'Brandon Oberdorfer'))}</span></div></div>
  <div><code>property</code><p class="meta">${esc(settings.attribution.property)}<br>${esc(settings.attribution.listingCourtesy.replace('{listingOffice}', '[Listing office]'))}</p></div>
  <div><code>contact</code><p class="form__note">${esc(settings.attribution.contact)}</p></div>
  <div><code>disclosure</code><p class="meta">${esc(settings.attribution.disclosure)}</p></div>
  <div><code>collar</code><p class="meta">Prepared by <b style="font-family:var(--f-serif);color:var(--ink)">The Oberdorfer Team</b> · Brokered by ${esc(settings.brokerage.legalName)}</p></div>
</div></div></div>`)}
${chap('type', 8, 'Typography', 'A county-atlas serif for the voice, a highway-sign sans for the work, and a mono kept for coordinates.', `
<div class="bb-grid">
<div class="span-7 specimen"><div class="specimen__big" style="font-family:var(--f-serif);font-weight:800">Besley <em style="font-weight:400">Aa</em></div><div class="specimen__meta"><span>Display, headlines, voice, prices</span><span>400 · 400 italic · 600 · 800 · 800 italic</span><span>SIL OFL</span></div><p class="prose" style="margin-top:1rem">A Clarendon, the face of nineteenth-century American printing: county atlases, deed plans, railroad timetables. Its bracketed slabs feel built rather than drawn; its italic is unusually warm. Weight 800 carries headlines; italic 400 carries the turn of phrase.</p><p class="alphabet" style="font-family:var(--f-serif)">ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789 $&amp;?!</p></div>
<div class="span-5 specimen"><div class="specimen__big" style="font-family:var(--f-sans);font-weight:700">Overpass</div><div class="specimen__meta"><span>Interface, body, data</span><span>Variable 100–900</span><span>SIL OFL</span></div><p class="prose" style="margin-top:1rem">An open-source interpretation of Highway Gothic, the lettering of American road signs: the type you read at speed on the way to see a house. Clear at small sizes, tabular figures for data.</p><p class="alphabet" style="font-family:var(--f-sans)">ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789</p><p class="specimen__meta" style="margin-top:1.5rem;font-family:var(--f-mono)">Overpass Mono 500: coordinates · photo codes · MLS 7300101</p></div>
<div class="span-6"><h3>Scale</h3><ul class="scale">${[['display', 'var(--t-display)', 800, 'Find your place.'], ['h1', 'var(--t-h1)', 800, 'Selling, with a plan.'], ['h2', 'var(--t-h2)', 800, 'Six towns, one sheet'], ['h3', 'var(--t-h3)', 800, 'The facts'], ['lede', 'var(--t-lede)', 400, 'Homes, streets and towns across Central Massachusetts.']].map(([n, v, w, t]) => `<li><code>--t-${n}</code><span style="font:${w} ${v}/1.05 var(--f-serif);letter-spacing:-.02em">${t}</span></li>`).join('')}<li><code>--t-body</code><span>Body copy in Overpass at 17px, 1.6 leading, 66-character measure.</span></li><li><code>--t-label</code><span class="label">Labels · legends · table heads</span></li></ul></div>
<div class="span-6"><h3>Map lettering</h3><p class="prose" style="font-size:1rem;margin-bottom:1rem">Borrowed from survey conventions and used everywhere a place is named.</p><ul class="scale"><li><code>Town</code><span class="town" style="font-size:1.25rem">Shrewsbury</span></li><li><code>Water</code><span class="water-name" style="font-size:1.25rem">Lake Quinsigamond</span></li><li><code>Coordinates</code><span class="code">42°16′N  71°48′W</span></li><li><code>Halo</code><span class="town halo" style="font-size:1.1rem;background:repeating-linear-gradient(110deg,var(--contour) 0 1px,transparent 1px 7px);padding:.3rem .5rem">Grafton</span></li></ul></div>
<div class="span-12"><h3>Real-estate data hierarchy</h3><div class="datatype"><div><dl>
  <div><dt>Price · Besley 800 · --t-price · lining figures</dt><dd class="price">$574,000</dd></div>
  <div><dt>Address · Besley 600 · 19px</dt><dd class="address">6 Shore Walk</dd></div>
  <div><dt>Town · spaced roman caps</dt><dd class="town meta">Shrewsbury, MA 01545</dd></div></dl></div><div><dl>
  <div><dt>Facts · Overpass 600 tabular · units in 400</dt><dd>${L.facts(listings[1])}</dd></div>
  <div><dt>Status · Overpass 700 caps + map symbol</dt><dd style="display:flex;gap:1rem;flex-wrap:wrap">${['Active', 'Open house', 'Coming soon', 'Under agreement'].map(s => `<span class="status" data-status="${s}">${s}</span>`).join('')}</dd></div>
  <div><dt>Identifiers · Overpass Mono</dt><dd class="code">MLS 7300102 · PR-06</dd></div></dl></div></div></div>
</div>`)}
${chap('color', 9, 'Color', 'The layers of a survey sheet: paper, contour, woodland, water, and one red route. Forest carries the brand; route red is spent only on the main way forward.', `
<div class="bb-grid"><div class="span-12"><h3>Proportion on a typical page</h3><div class="proportion" aria-hidden="true"><span style="flex:58;background:var(--paper)">paper 58</span><span style="flex:14;background:var(--forest);color:var(--paper)">forest 14</span><span style="flex:10;background:var(--woodland)">woodland 10</span><span style="flex:10;background:var(--ink);color:var(--paper)">ink 10</span><span style="flex:4;background:var(--contour)">4</span><span style="flex:2;background:var(--water)"></span><span style="flex:2;background:var(--route)"></span></div></div>
<div class="span-12"><div class="swatches">${Object.entries(C).map(([k, v]) => { const dark = ['forest', 'forest-deep', 'ink', 'ink-soft', 'water', 'route', 'route-deep', 'contour-ink'].includes(k); return `<div class="swatch"><div class="swatch__chip" style="background:var(--${k});color:${dark ? 'var(--paper)' : 'var(--ink)'}">${k}</div><div class="swatch__meta"><b>${k.replace(/-/g, ' ')}</b><span>${v.oklch}</span><span>${v.hex}</span><span class="swatch__role">${swatchRoles[k] || ''}</span></div></div>`; }).join('')}</div></div>
<div class="span-7"><h3>Contrast (WCAG 2.2)</h3><table class="ratio-table"><thead><tr><th>Pair</th><th>Sample</th><th class="num">Ratio</th><th>Use</th></tr></thead><tbody>${palette.contrast.map(c => `<tr><td>${c.fg} on ${c.bg}</td><td><span class="sample" style="color:var(--${c.fg});background:var(--${c.bg})">Aa</span></td><td class="num">${c.ratio.toFixed(2)}:1</td><td>${c.ratio >= 4.5 ? '<span class="pass">Text</span>' : c.ratio >= 3 ? '<span class="large">Large text & marks</span>' : 'Decoration'}</td></tr>`).join('')}</tbody></table></div>
<div class="span-5 prose"><h3>Rules</h3><p>Forest is a field, not an accent: it owns whole bands. Route red appears once per view as the primary action, and on selected states. Contour brown is linework only; when it must be text, use contour-ink. Water blue is for links and information, never for buttons.</p><p>Colors are authored in OKLCH so lightness steps are perceptually even; hex values are fallbacks for print and email.</p></div></div>`)}
${chap('photography', 10, 'Photography', 'Documentary, observational, warm. Three categories, each with its own frame color in layouts until real photography arrives.', `
<div class="bb-grid">
<div class="span-4">${frame(p, { kind: 'property', code: 'PR-02', direction: listings[0].photos[1].direction, ar: '4 / 5' })}<h3 style="margin-top:1rem">Property</h3><p class="meta">Interiors, exteriors, details, materials, light. Level verticals, available light, rooms that look lived in, not staged to sterility.</p></div>
<div class="span-4">${frame(p, { kind: 'place', code: 'PL-03', direction: towns[2].photo.direction, ar: '4 / 5', seed: 3 })}<h3 style="margin-top:1rem">Place</h3><p class="meta">Streets, centers, parks, water, stone walls, the drive. Shot in specific seasons and hours, named in captions.</p></div>
<div class="span-4">${frame(p, { kind: 'people', code: 'PE-02', direction: agents[1].portrait.direction, ar: '4 / 5' })}<h3 style="margin-top:1rem">People</h3><p class="meta">The team at work: mid-sentence, walking, pointing at a detail. Clients from behind or in hands-and-paper details unless they’ve agreed otherwise.</p></div>
<div class="span-6"><div class="pair"><div class="no"><h3 class="h4">${icon(p, 'close')}Never</h3><p>People holding keys. Handshakes. Arms-crossed portraits. Stock families on lawns. Drone shots with lens flare. Twilight-sky replacements. HDR halos.</p></div><div class="yes"><h3 class="h4">${icon(p, 'check')}Always</h3><p>Natural light, real seasons, true color. Captions that say where and when. One decisive frame over five similar ones.</p></div></div></div>
<div class="span-6 prose"><p>Until the shoot happens, every image slot on the site is an <b>art-directed frame</b>: a tinted plate carrying its code, its aspect ratio and a one-line brief. The frames are the shot list. Hand this chapter to the photographer.</p></div>
<div class="span-12"><h3>Shot list (${allShots.length} frames in this concept)</h3><div class="shotlist-wrap"><table class="shotlist"><thead><tr><th>Code</th><th>Category</th><th>Brief</th><th>Used on</th></tr></thead><tbody>${allShots.map(s => `<tr><td>${esc(s.code)}</td><td>${esc(s.kind)}</td><td class="dir">${esc(s.direction)}</td><td>${esc(s.use)}</td></tr>`).join('')}</tbody></table></div></div>
</div>`)}
${chap('cartography', 11, 'The sheet', 'The system’s signature. Every page is a sheet: a neatline frames the ground, a collar carries the credits, a legend explains the choices, and adjoining sheets lead next door.', `
<div class="bb-grid">
<div class="span-7"><div class="motion-demo" style="aspect-ratio:16/10"><div class="mapbox"><div class="stage stage--cover">${terrainSvg(p, { aspect: 'xMidYMid meet' })}${terrain.towns.map(t => `<span class="town-pin" style="--x:${t.x};--y:${t.y};pointer-events:none"><span class="town halo">${t.name}</span></span>`).join('')}<span class="water-label water-name halo" style="--x:.533;--y:.38;--rot:-84deg">Lake Quinsigamond</span></div></div></div><p class="meta" style="margin-top:.6rem">Terrain is generated (tools/terrain.mjs, seed 1874): illustrative, shaped to echo the region: higher ground toward Holden, drumlin hills around Worcester, the Lake Quinsigamond trough and the Blackstone valley. It is never presented as survey data.</p></div>
<div class="span-5"><ul class="ruled"><li><b>Neatline</b><span>1.5px ink rule around the main sheet, with coordinate ticks at the corners on wide screens.</span></li><li><b>Collar</b><span>Header and footer sit outside the neatline, like a sheet’s margins. Credits, brokerage and legal live here.</span></li><li><b>Contours</b><span>Minor lines at 42% opacity, index lines (every fifth) heavier. Quiet on content, full on openings.</span></li><li><b>Legend</b><span>Choices are legend entries: a symbol, a name, a note. Intents on the homepage, attributes in discovery, filters in search.</span></li><li><b>Adjoining sheets</b><span>Town pages name their neighbors at the N/E/S/W edges; each name links to that town.</span></li><li><b>Lettering</b><span>Towns in spaced roman caps with a paper halo; water in blue italic.</span></li></ul></div>
<div class="span-12"><h3>Legend symbols</h3><div class="comp-board"><div class="comp-row">${[['route', 'Buying · primary route'], ['double', 'Selling'], ['dashed', 'Relocating'], ['contour', 'Exploring'], ['water', 'Advice'], ['area', 'More space'], ['hatch', 'Older homes'], ['solid', 'Newer construction'], ['parcel', 'Larger lots'], ['dot', 'Walkable center'], ['ring', 'Closer to Worcester'], ['rail', 'Commuter rail']].map(([s, l]) => `<span style="display:inline-flex;gap:.6rem;align-items:center;min-width:220px">${sym(s)}<span>${l}</span></span>`).join('')}</div></div></div>
</div>`)}
${chap('layout', 12, 'Layout <em>& grid</em>', 'Twelve columns inside the neatline; the collar is the margin.', `
<div class="bb-grid"><div class="span-12"><div class="gridviz" aria-hidden="true">${'<span></span>'.repeat(12)}</div><p class="meta" style="margin-top:.6rem">12 columns · gutter clamp(16px, 2.2vw, 32px) · collar clamp(10px, 2.6vw, 40px) · max content 1520px · reading measure 66ch</p></div>
<div class="span-6"><h3>Rhythm</h3><ul class="ruled"><li><b>Sections</b><span>clamp(4rem, 6vw, 8rem) vertical padding; more space above a heading than below it.</span></li><li><b>Section heads</b><span>Heading across seven columns, a supporting note across the last five. No kicker labels above headings.</span></li><li><b>Pace</b><span>Alternate paper, forest and woodland fields; a dense table earns a quiet frame next.</span></li></ul></div>
<div class="span-6"><h3>Edges, not cards</h3><ul class="ruled"><li><b>Shared borders</b><span>Groups share rules like a sheet index, rather than floating as rounded cards.</span></li><li><b>Corners</b><span>2px radius. Paper has corners.</span></li><li><b>Depth</b><span>Only for things lifted off the sheet: the town preview, dialogs, the map-toggle button.</span></li></ul></div></div>`)}
${chap('components', 13, 'Components', 'Live components from the site, rendered from the same CSS.', `
<div class="bb-grid">
<div class="span-6"><span class="comp-cap">Buttons</span><div class="comp-board"><div class="comp-row"><a class="btn btn--route" href="#components">Schedule a showing ${icon(p, 'arrow')}</a><a class="btn btn--line" href="#components">Ask about this home</a></div><div class="comp-row"><a class="link-arrow" href="#components">Read the story ${icon(p, 'arrow')}</a><button class="fav" type="button" aria-pressed="true" aria-label="Saved example" style="--icon-fill:var(--route)">${icon(p, 'heart')}</button><button class="fav" type="button" aria-pressed="false" aria-label="Save example">${icon(p, 'heart')}</button></div><div class="comp-row on-forest" style="padding:1rem"><a class="btn btn--paper" href="#components">Talk with Brandon &amp; Kait ${icon(p, 'arrow')}</a><a class="btn btn--ghost-paper" href="#components">Meet the team</a></div></div></div>
<div class="span-6"><span class="comp-cap">Legend chips (toggle)</span><div class="comp-board"><div class="chips">${journeys.attributes.slice(0, 5).map((a, i) => `<button class="chip" type="button" aria-pressed="${i === 1}">${sym(a.symbol)}${a.label}</button>`).join('')}</div><span class="comp-cap">Form field</span><div class="field"><label for="demo-f">Email</label><input id="demo-f" placeholder="you@example.com"></div><div class="field" data-invalid><label for="demo-g">First name</label><input id="demo-g" aria-invalid="true"><span class="error">Please tell us your first name.</span></div></div></div>
<div class="span-12"><span class="comp-cap">Listing rows (search mode)</span>${L.rowsTable(p, listings.slice(0, 3), { caption: 'Example rows' }).replace(/href="\.\.\/site/g, 'href="../site')}</div>
<div class="span-7"><span class="comp-cap">Verified data block</span><div class="datablock"><div class="datablock__head"><span class="label" style="color:var(--ink)">Property record</span><span class="synthetic">Sample data</span></div><dl><div><dt>Year built</dt><dd>1957</dd></div><div><dt>Living area</dt><dd>1,720 sq ft</dd></div><div><dt>Heating</dt><dd>Gas, forced air</dd></div><div><dt>MLS #</dt><dd>7300102</dd></div></dl><p class="datablock__foot">Source line, listing courtesy and MLS disclaimer always close the block.</p></div></div>
<div class="span-5"><span class="comp-cap">Person line (contact a named human)</span><div class="comp-board">${L.personLine(p, agents[0])}</div></div>
<div class="span-12"><span class="comp-cap">Journey profile (buying)</span><div class="comp-board">${L.journeyBlock(p, 'buying', { id: 'bb-buying', linkAll: false })}</div></div>
</div>`)}
${chap('motion', 14, 'Motion', 'One authored moment per surface. Motion reveals the map and the place; it never decorates.', `
<div class="bb-grid"><div class="span-7"><div class="motion-demo" data-motion-demo><div class="mapbox"><div class="stage stage--cover">${terrainSvg(p, { aspect: 'xMidYMid meet', draw: true })}</div></div><button class="btn btn--line btn--small replay" type="button" data-replay>Replay draw-in</button></div></div>
<div class="span-5"><ul class="ruled"><li><b>Contour draw-in</b><span>Openings draw their terrain once on load: minor lines over 1.8s, index lines slightly after, water last. Exponential ease-out.</span></li><li><b>Town lift</b><span>Hover or focus a town and its hill darkens through a widening clip circle (700ms) while a preview of the place appears beside it.</span></li><li><b>Frame reveal</b><span>Photographs open top-down like a print pulled from a tray (1.1s), once, as they enter.</span></li><li><b>Sheet transitions</b><span>Cross-document view transitions between pages; listing hero frames carry their own transition name.</span></li><li><b>Reduced motion</b><span>Everything above is skipped; content is visible by default and never waits for an animation.</span></li></ul><p class="meta" style="margin-top:1rem">Never: bounce, scroll hijacking, parallax, staggered fade-ins on every section.</p></div></div>`)}
${chap('accessibility', 15, 'Accessibility <em>& fairness</em>', 'WCAG 2.2 AA as a floor, and fair-housing language as a rule.', `
<div class="bb-grid"><div class="span-6"><ul class="ruled"><li><b>Contrast</b><span>Body text ≥ 4.5:1; ink-faint and contour only for large type and marks.</span></li><li><b>Focus</b><span>2.5px water-blue outline with 3px offset; paper on dark fields. Never removed.</span></li><li><b>Targets</b><span>44px minimum for controls; 40px for compact chips with spacing.</span></li><li><b>Keyboard</b><span>Journeys and filters are real tabs and inputs; dialogs are native, trap focus and close on Escape.</span></li><li><b>Screen readers</b><span>Photo frames announce their brief; map pins are links with full names; results counts are live regions.</span></li><li><b>Motion</b><span>prefers-reduced-motion removes every animation.</span></li></ul></div>
<div class="span-6"><div class="pair"><div class="no"><h3 class="h4">${icon(p, 'close')}Never</h3><p>“Family-friendly,” “safe neighborhood,” “young professionals,” “great schools” as a selling point, or any description of who lives somewhere.</p></div><div class="yes"><h3 class="h4">${icon(p, 'check')}Instead</h3><p>Describe housing, lots, distances, transit, parks and places. Let people judge fit for themselves, and offer to answer specific questions.</p></div></div><p class="meta" style="margin-top:1rem">${esc(settings.fairHousing)}</p></div></div>`)}
${chap('tokens', 16, 'Design <em>tokens</em>', 'One source of truth for the concept, the brand book and the WordPress theme.', `
<div class="bb-grid"><div class="span-7"><pre class="tokens-pre">${esc(readFileSync(new URL('../assets/css/tokens.css', import.meta.url), 'utf8').split(':root {')[1].split('\n}')[0]).replace(/(--[a-z0-9-]+)/g, '<span class="k">$1</span>')}</pre></div>
<div class="span-5 prose"><p>Tokens ship three ways: CSS custom properties (<code>assets/css/tokens.css</code>), a JSON file for any tool, and a <code>theme.json</code> palette, type and spacing preset for the block theme.</p><div class="dl-list" style="margin-top:1rem"><a class="btn btn--line btn--small" href="${p}assets/css/tokens.css" download>tokens.css</a><a class="btn btn--line btn--small" href="${p}assets/brand/tokens.json" download>tokens.json</a><a class="btn btn--line btn--small" href="${p}assets/brand/theme.json" download>theme.json</a></div></div></div>`)}
${chap('model', 17, 'Content <em>model</em>', 'Structured content and relationships, so a new agent or town is an entry, not a page build.', `
<div class="bb-grid"><div class="span-12 relations">${relSvg}</div>
<div class="span-12"><div class="model">
<div><h3 class="h4">Agent</h3><code>CPT agent · /agents/{slug}/</code><ul><li>name, role, license, portrait (+ brief)</li><li>intro, bio, quote, specialties, credentials</li><li>phone, email, social</li><li>→ areas (Community, many)</li><li>→ listings (by agent ID from IDX)</li><li>→ articles (author)</li></ul></div>
<div><h3 class="h4">Community</h3><code>CPT community · /communities/{slug}/</code><ul><li>lede, overview, housing types, places</li><li>getting around, adjoining towns</li><li>attributes (neutral taxonomy)</li><li>sheet position (x, y) for maps</li><li>→ agents, guides, IDX saved query</li></ul></div>
<div><h3 class="h4">Property</h3><code>IDX normalized record · /homes/{slug}/</code><ul><li>MLS fields displayed as received</li><li>optional Story (team-written, signed)</li><li>photos with briefs until shot</li><li>→ agent, community</li><li>vendor adapter: any IDX feed</li></ul></div>
<div><h3 class="h4">Guide</h3><code>post type post · category taxonomy</code><ul><li>title, dek, body blocks, photo</li><li>author → Agent</li><li>→ communities (many)</li></ul></div>
<div><h3 class="h4">Market update</h3><code>CPT market_update</code><ul><li>period, community, figures with source + date</li><li>no figure publishes without a source</li></ul></div>
<div><h3 class="h4">Brokerage settings</h3><code>options page</code><ul><li>legal name, address, license notes</li><li>attribution strings by context</li><li>IDX disclaimer, fair-housing text</li><li>swap affiliation without a rebuild</li></ul></div>
</div></div>
<div class="span-12"><h3>Lead routing metadata</h3><p class="prose" style="font-size:1rem">Every form sends the same shape to Follow Up Boss: person (name, email, phone, tags), type (Property / Seller / General Inquiry), message, property (address, MLS #, price, URL), campaign (UTM, first touch), page URL, and a routing block: agent (from an agent page, a listing’s agent, or the visitor’s choice), community and intent. Agent-level attribution; team-level rules decide who replies.</p><p style="margin-top:1rem"><a class="link-arrow" href="${p}site/homes/6-shore-walk-shrewsbury/#ask">Try a form and see the payload ${icon(p, 'arrow')}</a></p></div></div>`)}
</div></div>`;

const bookHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Brand book · The Oberdorfer Team · Concept 2</title><meta name="description" content="The Oberdorfer Team brand book, Concept 2: The Quadrangle."><link rel="icon" href="${p}assets/brand/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${p}assets/css/brand.css"><script>document.documentElement.classList.add('js')</script></head>
<body data-root="${p}"><a class="skip" href="#main">Skip to content</a>
<header class="bb-top"><div class="bb-top__bar">${L.lockup(p)}<span class="bb-top__title">Brand book · Concept 2</span><nav aria-label="Concept"><a href="${p}">Concept index</a><a href="${p}site/">Website →</a></nav></div></header>
<main id="main" class="sheet" tabindex="-1" style="margin-top:var(--collar)">${body}</main>
<footer class="collar-bottom" style="display:block;padding-block:var(--s-6)"><p class="meta">${esc(settings.attribution.footer)} Concept prepared by Jeremy Anderson · jeremyanderson.tech · October 2026.</p></footer>
<div class="toast" role="status" aria-live="polite" data-toast></div>
<script src="${p}assets/js/site.js" defer></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{const links=[...document.querySelectorAll('.bb-toc a')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('is-current',l.getAttribute('href')==='#'+e.target.id));}}),{rootMargin:'-40% 0px -55% 0px'});document.querySelectorAll('.chapter').forEach(c=>io.observe(c));
document.querySelector('[data-replay]')?.addEventListener('click',()=>{const t=document.querySelector('[data-motion-demo] .terrain');t.classList.remove('terrain--draw');void t.offsetWidth;t.classList.add('terrain--draw');});});
</script></body></html>`;
W('brand/index.html', bookHtml);

// ---------------------------------------------------------------- concept index
const idx = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>The Oberdorfer Team · Concept 2 · The Quadrangle</title><meta name="description" content="Brand book and website concept for The Oberdorfer Team at REWAP Brokerage."><link rel="icon" href="assets/brand/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/brand.css"></head>
<body data-root=""><main class="sheet" style="margin-top:var(--collar)">
<section class="bb-cover" aria-labelledby="ix-h" style="min-height:calc(100svh - 2 * var(--collar))">
  <div class="mapbox" aria-hidden="true"><div class="stage stage--cover">${terrainSvg('', { aspect: 'xMidYMid meet', draw: true })}${terrain.towns.filter(t => t.x > 0.45 && t.y < 0.75).map(t => `<span class="town-pin" style="--x:${t.x};--y:${t.y};pointer-events:none"><span class="town halo">${t.name}</span></span>`).join('')}</div></div>
  <div class="bb-cover__inner">
    <div style="grid-column:1/-1">${L.lockup('', { href: 'site/' })}</div>
    <h1 id="ix-h" style="margin-top:var(--s-6)">Concept 2 <em>The Quadrangle.</em></h1>
    <p>A brand and website concept for The Oberdorfer Team at REWAP Brokerage, built on the idea of framing place: every page a survey sheet of Central Massachusetts, read with the people who know it.</p>
    <div style="grid-column:1/span 8;margin-top:var(--s-6);display:flex;flex-wrap:wrap;gap:.75rem"><a class="btn btn--route" href="brand/">Open the brand book ${icon('', 'arrow')}</a><a class="btn btn--line" href="site/">Open the website ${icon('', 'arrow')}</a><a class="btn btn--line" href="https://github.com/CptNope/The-Oberdorfer-Team-Concept-2#readme">README</a></div>
  </div>
  <nav class="opening__legend" aria-label="Pages in the concept" style="grid-template-columns:repeat(5,minmax(0,1fr))">${[['Homepage', 'site/', 'contour', 'The opening sheet, intents, towns, routes.'], ['Search', 'site/search/', 'route', 'Search and Discover modes, map, filters, saves.'], ['Property story', 'site/homes/128-chester-hill-road-holden/', 'double', 'Editorial story, separated from verified data.'], ['Town sheet', 'site/communities/grafton/', 'dashed', 'Housing, places, getting around, neighbors.'], ['Agent page', 'site/agents/brandon-oberdorfer/', 'water', 'One publication, many contributors.']].map(([n, h, s, note]) => `<a class="intent" href="${h}">${sym(s)}<span class="intent__name">${n}${icon('', 'arrow')}</span><span class="intent__note">${note}</span></a>`).join('')}</nav>
  <div class="opening__collar"><span class="credit">Prepared for <b>Brandon &amp; Kait Oberdorfer</b> by Jeremy Anderson</span><span>October 2026 · all listings, figures and bios are labeled samples</span></div>
</section></main></body></html>`;
W('index.html', idx);
console.log('brand book, tokens, theme.json and index written');
